# Image processing configuration

# Verbosity setting
verbose: true  # If True, print extra logging.

# Camera model selection
camera_type: perspective  # Options: perspective, fisheye, equirectangular, pinhole, simple_pinhole

# Feature matching method
matching_method: vocab_tree  # Options: exhaustive, sequential, vocab_tree
# Vocab tree is recommended for a balance of speed and accuracy.
# Exhaustive is slower but more accurate.
# Sequential is faster but should only be used for videos.

# Structure from motion tool
sfm_tool: colmap  # Options: any, colmap, hloc
# Colmap will use sift features, hloc can use many modern methods such as superpoint features and superglue matcher

# Refinement options
refine_pixsfm: false  # If True, runs refinement using Pixel Perfect SFM. Only works with hloc sfm_tool
refine_intrinsics: true  # If True, do bundle adjustment to refine intrinsics. Only works with colmap sfm_tool

# Feature and matcher types
feature_type: any  # Options: any, sift, superpoint, superpoint_aachen, superpoint_max, superpoint_inloc, r2d2, d2net-ss, sosnet, disk
matcher_type: any  # Options: any, NN, superglue, superglue-fast, NN-superpoint, NN-ratio, NN-mutual, adalam, disk+lightglue, superpoint+lightglue

# Image processing
num_downscales: 0 # Number of times to downscale the images. Downscales by 2 each time.
skip_colmap: false  # If True, skips COLMAP and generates transforms.json if possible.
skip_image_processing: false  # If True, skips copying and downscaling of images and only runs COLMAP if possible and enabled

# GPU usage
gpu: true  # If True, use GPU.

# Depth-related settings
use_sfm_depth: false  # If True, export and use depth maps induced from SfM points.
include_depth_debug: false  # If use_sfm_depth and this flag is True, also export debug images showing SfM overlaid upon input images.

# Image dimension assumptions
same_dimensions: true  # Whether to assume all images are same dimensions and so to use fast downscaling with no autorotation.

# Camera mode
use_single_camera_mode: true  # Whether to assume all images taken with the same camera characteristics, set to False for multiple cameras in colmap (only works with hloc sfm_tool).

# Image cropping
percent_radius_crop: 1.0  # Create circle crop mask. The radius is the percent of the image diagonal.

keep_original_world_coordinate: true